/* pages/advisor.js — AI-powered strategy recommendation & creation */
"use strict";
import { startPage } from "../../app/page.js";
import { U } from "../../core/utils.js";
import { openBuilder } from "../builder.js";

startPage("advisor", {
  mount(container, view, { kit, charts, shared, user }) {
    const advisor = container.advisor;
    const ai = container.ai;
    const svc = container.strategies;
    const summary = advisor.marketSummary();

    let html = '<div class="view-head"><div><h1>AI Advisor</h1><p>Get strategy recommendations matched to current gold market conditions — from the built-in local engine, or generated by an LLM you connect.</p></div></div>';
    if (!summary) {
      html += '<div class="card"><div class="empty"><div class="big">◧</div>Load market data first.</div></div>';
      view.innerHTML = html;
      return;
    }
    const trendBadge = { bull: '<span class="badge ok">BULL</span>', bear: '<span class="badge bad">BEAR</span>', side: '<span class="badge neutral">SIDEWAYS</span>' };
    const volCls = summary.volLabel === "high" ? "badge bad" : summary.volLabel === "low" ? "badge ok" : "badge warn";
    html += '<div class="card"><h3>Market snapshot <span class="sub">what the advisor sees</span></h3>' +
      '<div class="grid grid-4">' +
      '<div class="card stat-card"><div class="lab">Regime</div><div class="val" style="font-size:17px;margin-top:10px">' + trendBadge[summary.trend] + " <small>(" + summary.trendStrength + "% strength)</small></div></div>" +
      '<div class="card stat-card"><div class="lab">Annualized vol</div><div class="val">' + summary.annVol + '% <small class="' + (summary.volLabel === "high" ? "neg" : summary.volLabel === "low" ? "pos" : "") + '">' + summary.volLabel + "</small></div></div>" +
      '<div class="card stat-card"><div class="lab">ATR(14) %</div><div class="val">' + summary.atrPct + "%</div></div>" +
      '<div class="card stat-card"><div class="lab">60d / 20d return</div><div class="val" style="font-size:15px;margin-top:10px">' +
      '<span class="' + (summary.ret60 >= 0 ? "pos" : "neg") + '">' + U.signPct(summary.ret60) + "</span> / " +
      '<span class="' + (summary.ret20 >= 0 ? "pos" : "neg") + '">' + U.signPct(summary.ret20) + "</span></div></div>" +
      '<div class="card stat-card"><div class="lab">Regime mix (hist)</div><div class="val" style="font-size:14px;margin-top:10px">🟢' + summary.regimeMix.bull +
      "% 🔴" + summary.regimeMix.bear + "% ⚪" + summary.regimeMix.side + "%</div></div>" +
      '<div class="card stat-card"><div class="lab">52w range position</div><div class="val" style="font-size:16px;margin-top:10px">' + summary.rangePos + "%</div></div>" +
      '<div class="card stat-card"><div class="lab">Range low / high</div><div class="val" style="font-size:13px;margin-top:10px">$' + U.num(summary.rangeLo) + " / $" + U.num(summary.rangeHi) + "</div></div>" +
      '<div class="card stat-card"><div class="lab">Bars</div><div class="val">' + U.num(summary.bars, 0) + "</div></div></div>" +
      '<p class="muted small" style="margin:10px 0 0">' + U.esc(summary.summary) + "</p></div>";

    /* local recommendations */
    html += '<div class="card" style="margin-top:14px"><h3>Local engine recommendations <span class="sub">offline, deterministic</span></h3><div id="adv-local"></div></div>';

    /* AI generation */
    const cfg = ai.key() ? "configured" : "not configured";
    html += '<div class="card" style="margin-top:14px"><h3>Generate with an LLM <span class="sub">status: ' + cfg + "</span></h3>" +
      '<div class="frow">' +
      '<div class="field"><label>API base URL</label><input id="ai-base" placeholder="https://api.openai.com/v1" value="' + U.esc(ai.baseUrl()) + '"><div class="hint">OpenAI-compatible /chat/completions endpoint. OpenRouter or local gateways (Ollama, LM Studio) work from browsers; api.openai.com blocks browser CORS.</div></div>' +
      '<div class="field"><label>Model</label><input id="ai-model" placeholder="gpt-4o-mini" value="' + U.esc(ai.model()) + '"></div>' +
      '<div class="field"><label>API key</label><input id="ai-key" type="password" placeholder="' + (ai.key() ? "•••••••• (leave empty to keep current)" : "sk-…") + '"></div></div>' +
      '<div class="field"><label>Your goal / constraints (optional)</label><input id="ai-goal" placeholder="e.g. short-term trading, max 2% risk per trade, day-time only"></div>' +
      '<div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center">' +
      '<button class="btn btn-sm" id="ai-savecfg">Save settings</button>' +
      '<button class="btn btn-sm btn-danger" id="ai-clearkey">Clear key</button>' +
      '<span class="sp" style="flex:1"></span>' +
      '<button class="btn btn-primary" id="ai-gen">✨ Generate strategy</button></div>' +
      '<div id="ai-status" class="err-msg" style="margin-top:8px"></div>' +
      '<div class="muted small" style="margin-top:6px">The key is stored only in this browser (settings), never logged. The market snapshot and your recent results summary are sent to the model; nothing else leaves your machine.</div></div>';

    /* tweaks */
    html += '<div class="card" style="margin-top:14px"><h3>Tweak suggestions <span class="sub">based on your latest backtest</span></h3>' +
      '<div class="frow"><div class="field"><label>Strategy</label><select id="adv-tweak-sel">' +
      svc.all().map(s => '<option value="' + s.id + '">' + U.esc(s.name) + "</option>").join("") + "</select></div>" +
      '<div class="field" style="flex:0 0 auto"><label>&nbsp;</label><button class="btn btn-primary" id="adv-tweak-btn">Show suggestions</button></div></div>' +
      '<div id="adv-tweak-out"></div></div>';
    view.innerHTML = html;

    /* ------- local recs ------- */
    const recs = advisor.localRecommendations();
    const recHost = document.getElementById("adv-local");
    recHost.innerHTML = recs.length
      ? recs.map((r, i) => {
        const s = r.draft;
        const meta = svc.catalog().LOGIC_META[s.strategyLogic.type] || {};
        return '<div class="card" style="margin-bottom:10px"><div style="display:flex;gap:10px;align-items:flex-start;flex-wrap:wrap">' +
          '<div style="flex:1;min-width:240px"><b>' + U.esc(s.name) + '</b> <span class="badge info">' + U.esc(r.kind) + "</span>" +
          '<div class="muted small" style="margin-top:4px">' + U.esc(meta.label || "") + " · " + U.esc(JSON.stringify(s.strategyLogic.params)) + "</div>" +
          '<p class="small" style="color:var(--ink-2);margin:6px 0 0">' + U.esc(r.reasoning) + "</p></div>" +
          '<div style="flex:0 0 auto"><button class="btn btn-sm btn-primary" data-use="' + i + '">Use this</button></div></div></div>';
      }).join("")
      : "<div class='empty'>No recommendations (need market data).</div>";
    recHost.querySelectorAll("[data-use]").forEach(b => b.addEventListener("click", () => {
      const rec = recs[+b.getAttribute("data-use")];
      openPreview("Local engine — " + rec.kind, JSON.stringify({ name: rec.draft.name, strategyLogic: rec.draft.strategyLogic, riskManagement: rec.draft.riskManagement, capitalManagement: rec.draft.capitalManagement, reasoning: rec.reasoning }, null, 2));
    }));
    /* ------- AI settings & generation ------- */
    document.getElementById("ai-savecfg").addEventListener("click", () => {
      container.settings.set("ai_base", document.getElementById("ai-base").value.trim());
      container.settings.set("ai_model", document.getElementById("ai-model").value.trim());
      const k = document.getElementById("ai-key").value.trim();
      if (k) container.settings.set("ai_key", k);
      kit.toast("AI settings saved", "ok");
    });
    document.getElementById("ai-clearkey").addEventListener("click", () => {
      container.settings.set("ai_key", "");
      kit.toast("API key cleared", "ok");
      location.reload();
    });
    const statusEl = document.getElementById("ai-status");
    document.getElementById("ai-gen").addEventListener("click", () => {
      if (!ai.key()) {
        statusEl.textContent = "Add an API key above first — or use the local engine cards instead.";
        return;
      }
      const goal = document.getElementById("ai-goal").value.trim();
      const resultsBrief = container.results.list().slice(0, 6)
        .map(r => "· " + (r.strategy ? r.strategy.name : "Portfolio") + " -> " + U.round((r.metrics || {}).totalReturn, 2) + "% (" + ((r.metrics || {}).totalTrades || 0) + " trades)").join("\n");
      statusEl.textContent = "Generating with " + ai.model() + "… (may take 10-60s)";
      kit.busy(true, "Asking the model for a strategy…");
      ai.generateRecommendation({ marketSummary: summary.summary, resultsBrief, userGoal: goal })
        .then(res => {
          kit.busy(false);
          if (!res.ok) {
            statusEl.textContent = res.error || "Generation failed.";
            if (res.raw) kit.modal("<p class='muted'>Raw model output:</p><textarea rows='10' style='font-family:var(--mono);font-size:12px' readonly>" + U.esc(res.raw) + "</textarea>", { title: "Raw response", size: "lg" });
            return;
          }
          const norm = ai.normalizeDraft(res.draft, svc);
          if (!norm.ok) {
            statusEl.textContent = norm.error || (norm.errors ? norm.errors.join("; ") : "Draft invalid.");
            kit.modal("<p class='err-msg'>" + (norm.errors ? norm.errors.map(U.esc).join("<br>") : U.esc(norm.error || "")) + "</p><p class='muted'>Raw draft:</p><textarea rows='10' style='font-family:var(--mono);font-size:12px' readonly>" + U.esc(JSON.stringify(res.draft, null, 2)) + "</textarea>", { title: "Draft needs fixing", size: "lg" });
            return;
          }
          statusEl.textContent = "✓ Draft generated — review it below.";
          openPreview("LLM draft (" + ai.model() + ")", JSON.stringify(norm.strategy, null, 2), res.draft.reasoning);
        })
        .catch(e => { kit.busy(false); statusEl.textContent = (e && e.message) || "Generation failed."; });
    });

    /* ------- preview / save modal ------- */
    function openPreview(title, jsonStr, note) {
      const m = kit.modal(
        (note ? '<p class="muted small" style="margin-top:0">' + U.esc(String(note).slice(0, 400)) + "</p>" : "") +
        "<p class='muted small'>Review or edit the strategy JSON. Risk &amp; capital blocks are optional — defaults apply.</p>" +
        '<textarea id="pv-json" rows="16" style="font-family:var(--mono);font-size:12px">' + U.esc(jsonStr) + "</textarea>" +
        '<div id="pv-err" class="err-msg"></div>',
        { title: title, size: "lg" });
      const foot = document.createElement("div");
      foot.style.cssText = "display:flex;justify-content:flex-end;gap:8px;margin-top:12px;flex-wrap:wrap";
      foot.innerHTML = '<button class="btn" data-check="1">Validate</button>' +
        '<button class="btn btn-primary" data-save="1">💾 Save as strategy</button>';
      m.body.appendChild(foot);
      const errEl = m.body.querySelector("#pv-err");
      const parseEdit = () => {
        try { return { ok: true, value: JSON.parse(m.body.querySelector("#pv-json").value) }; }
        catch (e) { return { ok: false, msg: "JSON error: " + e.message }; }
      };
      const build = () => {
        const p = parseEdit();
        if (!p.ok) return { ok: false, msg: p.msg };
        return ai.normalizeDraft(p.value, svc);
      };
      foot.querySelector("[data-check]").addEventListener("click", () => {
        const res = build();
        if (!res.ok) {
          errEl.textContent = res.msg || (res.errors ? res.errors.join("; ") : "Invalid.");
          return;
        }
        const errs = svc.validate(res.strategy);
        errEl.classList.toggle("ok", !errs.length);
        errEl.textContent = errs.length ? "⚠ " + errs.join("; ") : "✓ Valid — ready to save.";
      });
      foot.querySelector("[data-save]").addEventListener("click", () => {
        const res = build();
        if (!res.ok) {
          errEl.textContent = res.msg || (res.errors ? res.errors.join("; ") : "Invalid.");
          return;
        }
        const saved = svc.save(res.strategy);
        if (!saved.ok) { errEl.textContent = saved.errors.join("; "); return; }
        container.log.add("INFO", container.actorId(), "STRATEGY_CREATE", "AI Advisor created strategy " + res.strategy.name);
        kit.toast("Strategy saved: " + res.strategy.name, "ok");
        foot.innerHTML = '<button class="btn btn-primary" data-run="1">▶ Run backtest</button>' +
          '<button class="btn" data-tune2="1">Fine-tune in builder</button>';
        foot.querySelector("[data-run]").addEventListener("click", () => {
          try { sessionStorage.setItem("bt_lastStrategy", res.strategy.id); } catch (e) { /* ignore */ }
          location.href = "backtest.html";
        });
        foot.querySelector("[data-tune2]").addEventListener("click", () => {
          m.close();
          openBuilder(container, { kit, charts }, res.strategy.id);
        });
        errEl.textContent = "";
      });
    }

    /* ------- tweaks ------- */
    const tweakSel = document.getElementById("adv-tweak-sel");
    document.getElementById("adv-tweak-btn").addEventListener("click", () => {
      const res = advisor.suggestTweaks(tweakSel.value);
      const out = document.getElementById("adv-tweak-out");
      if (!res.ok) { out.innerHTML = '<div class="err-msg">' + U.esc(res.msg) + "</div>"; return; }
      out.innerHTML = res.notes.map(n => "<div style='display:flex;gap:8px;padding:6px 2px;align-items:flex-start'>" +
        '<span style="color:var(--acc)">✦</span><span class="small">' + U.esc(n) + "</span></div>").join("");
    });
  }
});
